import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import {
  getDashboardStats,
  getUsers,
  getArtists,
  getBookings,
  getPayments,
  getPaymentSummary,
  getChords,
  getReviews,
} from "../services/adminApi";

const formatDate = (value) => {
  if (!value) return "N/A";
  return new Date(value).toLocaleString();
};

const formatMoney = (value) => {
  if (!value) return "Rs. 0";
  return `Rs. ${value}`;
};

const getLoggedAdmin = () => {
  try {
    const savedAdmin = localStorage.getItem("adminUser");
    return savedAdmin ? JSON.parse(savedAdmin) : null;
  } catch {
    return null;
  }
};

const addHeader = (doc, title, role) => {
  const admin = getLoggedAdmin();

  doc.setFontSize(18);
  doc.text(title, 14, 18);

  doc.setFontSize(10);
  doc.text(`Generated by: ${admin?.name || "N/A"}`, 14, 26);
  doc.text(`Role: ${role}`, 14, 32);
  doc.text(`Generated at: ${new Date().toLocaleString()}`, 14, 38);

  doc.line(14, 43, 196, 43);
};

const addSectionTitle = (doc, title, y) => {
  if (y > 260) {
    doc.addPage();
    y = 18;
  }

  doc.setFontSize(13);
  doc.text(title, 14, y);

  return y + 5;
};

const addTable = (doc, title, columns, rows, startY) => {
  const titleY = addSectionTitle(doc, title, startY);

  autoTable(doc, {
    head: [columns],
    body: rows,
    startY: titleY,
    styles: {
      fontSize: 8,
      cellPadding: 2,
    },
    headStyles: {
      fillColor: [79, 140, 255],
    },
    alternateRowStyles: {
      fillColor: [245, 246, 251],
    },
  });

  return doc.lastAutoTable.finalY + 10;
};

const safeArray = (data) => {
  return Array.isArray(data) ? data : [];
};

export const downloadRoleBasedReport = async () => {
  const admin = getLoggedAdmin();

  if (!admin) {
    alert("Please login again before downloading the report.");
    return;
  }

  const role = admin.role;
  const doc = new jsPDF("p", "mm", "a4");

  let y = 52;

  if (role === "admin") {
    addHeader(doc, "MusicHive Full Admin Report", "Admin");

    const [
      dashboardResult,
      usersResult,
      artistsResult,
      bookingsResult,
      paymentsResult,
      chordsResult,
      reviewsResult,
    ] = await Promise.allSettled([
      getDashboardStats(),
      getUsers(),
      getArtists(),
      getBookings(),
      getPayments(),
      getChords(),
      getReviews(),
    ]);

    const dashboard =
      dashboardResult.status === "fulfilled" ? dashboardResult.value : {};

    const users =
      usersResult.status === "fulfilled" ? safeArray(usersResult.value) : [];

    const artists =
      artistsResult.status === "fulfilled"
        ? safeArray(artistsResult.value)
        : [];

    const bookings =
      bookingsResult.status === "fulfilled"
        ? safeArray(bookingsResult.value)
        : [];

    const payments =
      paymentsResult.status === "fulfilled"
        ? safeArray(paymentsResult.value)
        : [];

    const chords =
      chordsResult.status === "fulfilled" ? safeArray(chordsResult.value) : [];

    const reviews =
      reviewsResult.status === "fulfilled"
        ? safeArray(reviewsResult.value)
        : [];

    y = addTable(
      doc,
      "System Summary",
      ["Metric", "Value"],
      [
        ["Total Users", dashboard.totalUsers || 0],
        ["Artists", dashboard.totalArtists || 0],
        ["Bands", dashboard.totalBands || 0],
        ["Bookings", dashboard.totalBookings || 0],
        ["Chords", dashboard.totalChords || 0],
        ["Reviews", dashboard.totalReviews || 0],
      ],
      y
    );

    y = addTable(
      doc,
      "Users",
      ["Name", "Email", "Role", "Status"],
      users.map((user) => [
        user.name || "N/A",
        user.email || "N/A",
        user.role || "N/A",
        user.isBlocked ? "Blocked" : "Active",
      ]),
      y
    );

    y = addTable(
      doc,
      "Artists and Bands",
      ["Name", "Email", "Role", "Location"],
      artists.map((artist) => [
        artist.name || "N/A",
        artist.email || "N/A",
        artist.role || "N/A",
        artist.artistProfile?.location || "N/A",
      ]),
      y
    );

    y = addTable(
      doc,
      "Bookings",
      ["Customer", "Artist/Band", "Date", "Booking Status", "Payment"],
      bookings.map((booking) => [
        booking.customer?.name || booking.customerUid || "N/A",
        booking.artist?.name || booking.artistUid || "N/A",
        booking.date || "N/A",
        booking.status || "N/A",
        booking.paymentStatus || "N/A",
      ]),
      y
    );

    y = addTable(
      doc,
      "Payments",
      ["Customer", "Artist/Band", "Payment", "Amount", "Paid At"],
      payments.map((payment) => [
        payment.customer?.name || payment.customerUid || "N/A",
        payment.artist?.name || payment.artistUid || "N/A",
        payment.paymentStatus || "N/A",
        formatMoney(payment.amountPaid || payment.price),
        formatDate(payment.paidAt),
      ]),
      y
    );

    y = addTable(
      doc,
      "Chords",
      ["Title", "Genre", "Owner", "Reviews", "Created"],
      chords.map((chord) => [
        chord.title || "Untitled",
        chord.genre || "N/A",
        chord.owner?.name || chord.uid || "N/A",
        chord.reviewCount || 0,
        formatDate(chord.createdAt),
      ]),
      y
    );

    y = addTable(
      doc,
      "Reviews",
      ["Reviewer", "Review For", "Rating", "Comment"],
      reviews.map((review) => [
        review.reviewerName || "N/A",
        review.reviewee?.name || review.revieweeUid || "N/A",
        `${review.rating || 0}/5`,
        review.comment || "N/A",
      ]),
      y
    );

    doc.save("MusicHive_Admin_Full_Report.pdf");
    return;
  }

  if (role === "manager") {
    addHeader(doc, "MusicHive Manager Report", "Manager");

    const [bookings, chords, reviews] = await Promise.all([
      getBookings(),
      getChords(),
      getReviews(),
    ]);

    y = addTable(
      doc,
      "Bookings",
      ["Customer", "Artist/Band", "Date", "Booking Status", "Payment"],
      safeArray(bookings).map((booking) => [
        booking.customer?.name || booking.customerUid || "N/A",
        booking.artist?.name || booking.artistUid || "N/A",
        booking.date || "N/A",
        booking.status || "N/A",
        booking.paymentStatus || "N/A",
      ]),
      y
    );

    y = addTable(
      doc,
      "Chords",
      ["Title", "Genre", "Owner", "Reviews", "Created"],
      safeArray(chords).map((chord) => [
        chord.title || "Untitled",
        chord.genre || "N/A",
        chord.owner?.name || chord.uid || "N/A",
        chord.reviewCount || 0,
        formatDate(chord.createdAt),
      ]),
      y
    );

    y = addTable(
      doc,
      "Reviews",
      ["Reviewer", "Review For", "Rating", "Comment"],
      safeArray(reviews).map((review) => [
        review.reviewerName || "N/A",
        review.reviewee?.name || review.revieweeUid || "N/A",
        `${review.rating || 0}/5`,
        review.comment || "N/A",
      ]),
      y
    );

    doc.save("MusicHive_Manager_Report.pdf");
    return;
  }

  if (role === "accountant") {
    addHeader(doc, "MusicHive Accountant Payment Report", "Accountant");

    const [summary, payments] = await Promise.all([
      getPaymentSummary(),
      getPayments(),
    ]);

    y = addTable(
      doc,
      "Payment Summary",
      ["Metric", "Value"],
      [
        ["Total Bookings", summary.totalBookings || 0],
        ["Paid Payments", summary.paidPayments || 0],
        ["Unpaid Payments", summary.unpaidPayments || 0],
        ["Refunded Payments", summary.refundedPayments || 0],
        ["Total Revenue", formatMoney(summary.totalRevenue || 0)],
      ],
      y
    );

    y = addTable(
      doc,
      "Payment Records",
      [
        "Customer",
        "Artist/Band",
        "Payment",
        "Amount",
        "Reference",
        "Paid At",
      ],
      safeArray(payments).map((payment) => [
        payment.customer?.name || payment.customerUid || "N/A",
        payment.artist?.name || payment.artistUid || "N/A",
        payment.paymentStatus || "N/A",
        formatMoney(payment.amountPaid || payment.price),
        payment.paymentRef || payment.payhereOrderId || "N/A",
        formatDate(payment.paidAt),
      ]),
      y
    );

    doc.save("MusicHive_Accountant_Payment_Report.pdf");
    return;
  }

  alert("Unknown role. Cannot generate report.");
};